### ISSUE TITLE
Test throws error

### ISSUE THREAD

**Issue by vja26** [PatWalters/Free-Wilson#2]
Hi, I tried to install and run this package, but it throws an error for the test suggested on the github page:

```
$ ../free_wilson.py all --scaffold scaffold.mol --in fw_mols.smi --act fw_act.csv --prefix test
Traceback (most recent call last):
  File "../free_wilson.py", line 20, in <module>
    from free_wilson_enumeration import free_wilson_enumeration
  File "/Users/venkaaj1/softwares/Free-Wilson-master/free_wilson_enumeration.py", line 19
    def read_input(model_file_name: str, vector_file_name: str) -> Tuple[object, object]:
                                  ^
SyntaxError: invalid syntax
```

Thanks

**Comment by vja26** [comment]
Got it to work with python3 and additional dependencies including pandas and rdkit.

**Comment by PatWalters** [comment]
Glad everything works, please let me know if you have questions
